package net.jerika.furmutage.config;

import java.util.*;

public class LatexTeamConfig {
    // Hardcoded teams
    private static final Set<String> WHITE_LATEX_ENTITIES = Set.of(
            "changed:pure_white_latex_wolf",
            "changed:latex_mutant_bloodcell_wolf",
            "changed:latex_snake",
            "changed:headless_knight",
            "changed:white_latex_knight_fusion",
            "changed:white_latex_wolf_female",
            "changed:white_latex_wolf_male",
            "changed:white_latex_knight",
            "changed:white_latex_centaur",
            "changed:behemoth_head",
            "changed:behemoth_hand_left",
            "changed:behemoth_hand_right",
            "changed:milk_pudding",
            "changed:pure_white_latex_wolf_pup",
            "changed:custom_latex",
            "furmutage:latex_mutant_family",
            "furmutage:tsc_drone",
            "furmutage:tsc_drone_boss",
            "furmutage:latex_mutant_bomber",
            "furmutage:white_latex_pig",
            "furmutage:white_latex_cow",
            "furmutage:white_latex_chicken",
            "furmutage:white_latex_sheep",
            "furmutage:white_latex_rabbit",
            "furmutage:white_latex_horse",
            "furmutage:white_latex_goat",
            "furmutage:white_latex_llama",
            "furmutage:white_latex_squid",
            "furmutage:white_latex_dolphin",
            "furmutage:withered_latex_pudding",
            "furmutage:giant_pure_white_latex",
            "furmutage:latex_exo_mutant",
            "furmutage:latex_blood_worm_mutant",
            "furmutage:loose_behemoth_hand",
            "furmutage:loose_squid_dog_limb",
            "furmutage:latex_tenticle_limbs_mutant",
            "furmutage:white_latex_bottle_projectile",
            "spore:biobloob",
            "spore:bloater",
            "spore:braiomil",
            "spore:braurei",
            "spore:brot",
            "spore:brute",
            "spore:busser",
            "spore:claw",
            "spore:delusioner",
            "spore:gastgaber",
            "spore:gazenbreacher",
            "spore:griefer",
            "spore:hevoker",
            "spore:hindenburg",
            "spore:howitzer",
            "spore:howler",
            "spore:hvindicator",
            "spore:illusion",
            "spore:inebriater",
            "spore:inf_contruct",
            "spore:inf_drowned",
            "spore:inf_evoker",
            "spore:inf_hazmat",
            "spore:inf_human",
            "spore:inf_husk",
            "spore:inf_pillager",
            "spore:inf_player",
            "spore:inf_villager",
            "spore:inf_vindicator",
            "spore:inf_wanderer",
            "spore:inf_witch",
            "spore:inquisitor",
            "spore:jagd",
            "spore:knight",
            "spore:lacerator",
            "spore:leaper",
            "spore:licker",
            "spore:mound",
            "spore:nuclea",
            "spore:ogre",
            "spore:plagued",
            "spore:protector",
            "spore:proto",
            "spore:reconstructor",
            "spore:saugling",
            "spore:scamper",
            "spore:scavenger",
            "spore:scent",
            "spore:sieger",
            "spore:slasher",
            "spore:specter",
            "spore:spit",
            "spore:spitter",
            "spore:stalker",
            "spore:thorn",
            "spore:tumoroid_nuke",
            "spore:umarmed",
            "spore:usurper",
            "spore:verva",
            "spore:vigil",
            "spore:volatile",
            "spore:wendigo",
            "the_ravenous:the_ravenous_1",
            "the_ravenous:the_ravenous_2",
            "the_ravenous:the_ravenous_3",
            "the_ravenous:the_ravenous_4",
            "the_ravenous:the_ravenous_5",
            "the_ravenous:the_ravenous_6",
            "the_ravenous:the_screecher",
            "undead_revamp2:bigsucker",
            "undead_revamp2:bomber",
            "undead_revamp2:clogger",
            "undead_revamp2:crackleball",
            "undead_revamp2:deadclogger",
            "undead_revamp2:flame",
            "undead_revamp2:invisiblebidy",
            "undead_revamp2:invisiclogger",
            "undead_revamp2:invisiimmortal",
            "undead_revamp2:invisilehcery",
            "undead_revamp2:lechery",
            "undead_revamp2:neocrorines",
            "undead_revamp2:propball_1",
            "undead_revamp2:slaveman",
            "undead_revamp2:smokesmitter",
            "undead_revamp2:sucker",
            "undead_revamp2:the_moonflower",
            "undead_revamp2:thebeartamer",
            "undead_revamp2:thebidy",
            "undead_revamp2:thebidyupside",
            "undead_revamp2:thedungeon",
            "undead_revamp2:thegliter",
            "undead_revamp2:theheavy",
            "undead_revamp2:thehorrors",
            "undead_revamp2:thehorrorsdecoys",
            "undead_revamp2:thehunter",
            "undead_revamp2:theimmortal",
            "undead_revamp2:thelurker",
            "undead_revamp2:theordure",
            "undead_revamp2:theposessive",
            "undead_revamp2:thepregnant",
            "undead_revamp2:therabidus",
            "undead_revamp2:therod",
            "undead_revamp2:theskeeper",
            "undead_revamp2:thesmoker",
            "undead_revamp2:thesomnolence",
            "undead_revamp2:thespectre",
            "undead_revamp2:thespitter",
            "undead_revamp2:theswarmer",
            "undead_revamp2:thewolf",
            "undead_revamp2:weakspot",
            "zoniex:blood_eagle",
            "zoniex:brutaliser",
            "zoniex:disemboweler",
            "zoniex:skin_crawler",
            "zoniex:spine_wrencher",
            "zoniex:tormented_zombie",
            "zombie_extreme:assasin_black_ops",
            "zombie_extreme:boomer",
            "zombie_extreme:chainsaw",
            "zombie_extreme:clicker",
            "zombie_extreme:crawler",
            "zombie_extreme:demolisher",
            "zombie_extreme:devestated",
            "zombie_extreme:divided",
            "zombie_extreme:explosive_infected",
            "zombie_extreme:faceless",
            "zombie_extreme:fetus",
            "zombie_extreme:goon",
            "zombie_extreme:infected",
            "zombie_extreme:infected_hazmat",
            "zombie_extreme:infected_juggernaut",
            "zombie_extreme:infected_military",
            "zombie_extreme:infected_police",
            "zombie_extreme:inflated",
            "zombie_extreme:military",
            "zombie_extreme:night_hunter",
            "zombie_extreme:parasite",
            "zombie_extreme:ram",
            "zombie_extreme:rat_king",
            "zombie_extreme:revived",
            "zombie_extreme:runner",
            "zombie_extreme:zero_patient"
    );
    
    private static final Set<String> DARK_LATEX_ENTITIES = Set.of(
            "changed:dark_latex_wolf_male",
            "changed:dark_latex_wolf_female",
            "changed:dark_latex_wolf_partial",
            "changed:dark_latex_wolf_pup",
            "changed:dark_latex_yufeng",
            "changed:latex_benign_wolf",
            "changed:phage_latex_wolf_female",
            "changed:phage_latex_wolf_male",
            "changed:dark_latex_double_yufeng",
            "changed:latex_crow",
            "furmutage:dark_latex_charger_mutant",
            "furmutage:latex_bacteria",
            "furmutage:dark_latex_bottle_projectile",
            "furmutage:dark_latex_cow",
            "furmutage:dark_latex_pig",
            "furmutage:dark_latex_squid",
            "furmutage:dark_latex_horse",
            "furmutage:dark_latex_rabbit",
            "furmutage:dark_latex_dolphin",
            "furmutage:dark_latex_sheep",
            "furmutage:dark_latex_goat",
            "furmutage:dark_latex_llama",
            "the_flesh_that_hates:bruteplaquecreatureone",
            "the_flesh_that_hates:flesh_boomer",
            "the_flesh_that_hates:flesh_cocoon",
            "the_flesh_that_hates:flesh_community",
            "the_flesh_that_hates:flesh_cow",
            "the_flesh_that_hates:flesh_dog",
            "the_flesh_that_hates:flesh_howler",
            "the_flesh_that_hates:flesh_human",
            "the_flesh_that_hates:flesh_human_head",
            "the_flesh_that_hates:flesh_hunter_three",
            "the_flesh_that_hates:flesh_hunter_two",
            "the_flesh_that_hates:flesh_justice",
            "the_flesh_that_hates:flesh_piece",
            "the_flesh_that_hates:flesh_pig",
            "the_flesh_that_hates:flesh_pillager",
            "the_flesh_that_hates:flesh_servant",
            "the_flesh_that_hates:flesh_sheep",
            "the_flesh_that_hates:flesh_suffer",
            "the_flesh_that_hates:flesh_villager",
            "the_flesh_that_hates:flesh_vindicator",
            "the_flesh_that_hates:plaquecontaminator",
            "the_flesh_that_hates:plaquecreaturebaseone",
            "the_flesh_that_hates:plaquecreatureone",
            "the_flesh_that_hates:plaquecreaturetwo",
            "the_flesh_that_hates:plaqueincubatorone",
            "the_flesh_that_hates:plaqueincubatorstart",
            "the_flesh_that_hates:plaquethreelegcreature"
    );
    
    public static Set<String> getWhiteLatexEntities() {
        return Collections.unmodifiableSet(WHITE_LATEX_ENTITIES);
    }
    
    public static Set<String> getDarkLatexEntities() {
        return Collections.unmodifiableSet(DARK_LATEX_ENTITIES);
    }
    
    public static int getTeamForEntity(String entityTypeId) {
        if (WHITE_LATEX_ENTITIES.contains(entityTypeId)) {
            return 1;
        } else if (DARK_LATEX_ENTITIES.contains(entityTypeId)) {
            return 2;
        }
        return 0;
    }
    
    public static boolean isEntityInTeam(String entityTypeId) {
        return getTeamForEntity(entityTypeId) != 0;
    }
}

